name = "mcpeapsunterstrichhd"
main = ".open-next/worker.js"
compatibility_date = "2025-11-21"
compatibility_flags = ["nodejs_compat", "no_nodejs_compat_v2"]

[build]
command = "bunx --bun bun run deploy"

[observability.logs]
enabled = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
