name = "mcpeapsunterstrichhd-dev"
compatibility_date = "2025-11-21"
compatibility_flags = [
  "nodejs_compat",
  "no_nodejs_compat_v2",
  "global_fetch_strictly_public",
]

[build]
command = "next build"

[observability.logs]
enabled = true

[assets]
directory = ".next"
